language: node_js
node_js:
- '8'
- '8.4'
- '6'
- '7'
- '9'
- '10'
- '11'
- '12'
script: npm test
env:
  global:
  - ENCRYPTION_LABEL: 3985cea5a61f
  - COMMIT_AUTHOR_EMAIL: openapi@bandwidth.com
deploy:
  provider: npm
  email: hi@dtolb.com
  api_key:
    secure: QsOhkofy49Q2hya3D1QlbGQnFK7eKuBPifygvNgIqN75aJT5mGPUFzLcYyLd+tLtnjIh/fOV+dFI+QAWJjJWa73C7y1pq8y7hD7VPd+jloZPegUOum0fqcM8sHyU5rJ8IIlqxpMHbJBSK4+l3+KmmOoWYcwxsksuD170uDA+Zpg=
  on:
    tags: true
    repo: Bandwidth/node-bandwidth
